# Generated by Django 5.2.7 on 2025-11-06 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_device_remove_item_device_mac_alter_item_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
