# Generated by Django 5.2.7 on 2025-11-07 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_device_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='device',
            name='width',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
