# Generated by Django 5.2.7 on 2025-11-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_device_height_alter_device_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='max_stock',
            new_name='min_stock',
        ),
    ]
