# Generated by Django 5.2.7 on 2025-11-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_max_stock_item_min_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='top_level',
            new_name='bottom_level',
        ),
    ]
