# Generated by Django 5.2.7 on 2025-11-11 14:00
from django.contrib.postgres.operations import TrigramExtension  # ← ADD THIS LINE
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0010_remove_item_created_at_device_created_at_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
