# Generated by Django 5.2.7 on 2025-11-19 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_item_device_historicaldevice_historicalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='left_box',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='left_box',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
